// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Implements a Genkit flow to collect user feedback on chatbot responses and improve AI empathy.
 *
 * - improveAIThroughFeedback - Collects user feedback to improve the AI's empathy.
 * - ImproveAIThroughFeedbackInput - The input type for the improveAIThroughFeedback function.
 * - ImproveAIThroughFeedbackOutput - The return type for the improveAIThroughFeedback function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveAIThroughFeedbackInputSchema = z.object({
  chatbotResponse: z.string().describe('The chatbot response to evaluate.'),
  userFeedback: z.string().describe('The user feedback on the chatbot response.'),
});

export type ImproveAIThroughFeedbackInput = z.infer<typeof ImproveAIThroughFeedbackInputSchema>;

const ImproveAIThroughFeedbackOutputSchema = z.object({
  updatedInstructions: z.string().describe('Updated instructions for the chatbot to improve empathy.'),
});

export type ImproveAIThroughFeedbackOutput = z.infer<typeof ImproveAIThroughFeedbackOutputSchema>;

export async function improveAIThroughFeedback(
  input: ImproveAIThroughFeedbackInput
): Promise<ImproveAIThroughFeedbackOutput> {
  return improveAIThroughFeedbackFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveAIThroughFeedbackPrompt',
  input: {schema: ImproveAIThroughFeedbackInputSchema},
  output: {schema: ImproveAIThroughFeedbackOutputSchema},
  prompt: `You are an AI assistant designed to improve the empathy of a chatbot.
  You will receive a chatbot response and user feedback on that response.
  Your task is to analyze the feedback and update the chatbot's instructions to improve its empathy in future responses.

  Chatbot Response: {{{chatbotResponse}}}
  User Feedback: {{{userFeedback}}}

  Based on this feedback, suggest updated instructions for the chatbot to improve its empathy:
  `,
});

const improveAIThroughFeedbackFlow = ai.defineFlow(
  {
    name: 'improveAIThroughFeedbackFlow',
    inputSchema: ImproveAIThroughFeedbackInputSchema,
    outputSchema: ImproveAIThroughFeedbackOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
