// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Implements a Genkit flow to collect user feedback on chatbot responses and improve AI empathy.
 *
 * - improveAIEmpatheticAbility - Collects user feedback to improve the AI's empathy.
 * - ImproveAIEmpatheticAbilityInput - The input type for the improveAIEmpatheticAbility function.
 * - ImproveAIEmpatheticAbilityOutput - The return type for the improveAIEmpatheticAbility function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveAIEmpatheticAbilityInputSchema = z.object({
  chatbotResponse: z.string().describe('The chatbot response to evaluate.'),
  userFeedback: z.string().describe('The user feedback on the chatbot response.'),
});

export type ImproveAIEmpatheticAbilityInput = z.infer<typeof ImproveAIEmpatheticAbilityInputSchema>;

const ImproveAIEmpatheticAbilityOutputSchema = z.object({
  updatedInstructions: z.string().describe('Updated instructions for the chatbot to improve empathy.'),
});

export type ImproveAIEmpatheticAbilityOutput = z.infer<typeof ImproveAIEmpatheticAbilityOutputSchema>;

export async function improveAIEmpatheticAbility(
  input: ImproveAIEmpatheticAbilityInput
): Promise<ImproveAIEmpatheticAbilityOutput> {
  return improveAIEmpatheticAbilityFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveAIEmpatheticAbilityPrompt',
  input: {schema: ImproveAIEmpatheticAbilityInputSchema},
  output: {schema: ImproveAIEmpatheticAbilityOutputSchema},
  prompt: `You are an AI assistant designed to improve the empathy of a chatbot.
  You will receive a chatbot response and user feedback on that response.
  Your task is to analyze the feedback and update the chatbot's instructions to improve its empathy in future responses.

  Chatbot Response: {{{chatbotResponse}}}
  User Feedback: {{{userFeedback}}}

  Based on this feedback, suggest updated instructions for the chatbot to improve its empathy:
  `,
});

const improveAIEmpatheticAbilityFlow = ai.defineFlow(
  {
    name: 'improveAIEmpatheticAbilityFlow',
    inputSchema: ImproveAIEmpatheticAbilityInputSchema,
    outputSchema: ImproveAIEmpatheticAbilityOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
